import 'package:dartz/dartz.dart';
import '../../../../core/errors/failures.dart';
import '../../../../core/usecases/usecase.dart';
import '../entities/mystery_entity.dart';
import '../repositories/mystery_repository.dart';

/// Use case for creating a new mystery booking
///
/// Handles the business logic for creating mystery bookings.
/// Validates input and delegates to the repository for data persistence.
class CreateMysteryUseCase extends UseCase<MysteryEntity, CreateMysteryParams> {
  /// Repository for mystery operations
  final MysteryRepository repository;

  CreateMysteryUseCase({required this.repository});

  @override
  Future<Either<Failure, MysteryEntity>> call(CreateMysteryParams params) async {
    return repository.createMystery(
      MysteryEntity(
        id: '', // ID will be generated by Firebase
        userId: params.userId,
        location: params.location,
        date: params.date,
        time: params.time,
        budgetMin: params.budgetMin,
        budgetMax: params.budgetMax,
        experienceType: params.experienceType,
        status: MysteryStatus.pending,
        createdAt: DateTime.now(),
      ),
    );
  }
}

/// Parameters for creating a mystery booking
class CreateMysteryParams {
  /// User ID creating the mystery
  final String userId;

  /// Location/city for the experience
  final String location;

  /// Date in yyyy-MM-dd format
  final String date;

  /// Time of day preference
  final MysteryTimeOfDay time;

  /// Minimum budget in dollars
  final double budgetMin;

  /// Maximum budget in dollars
  final double budgetMax;

  /// Preferred experience type
  final MysteryExperienceType experienceType;

  const CreateMysteryParams({
    required this.userId,
    required this.location,
    required this.date,
    required this.time,
    required this.budgetMin,
    required this.budgetMax,
    required this.experienceType,
  });
}
