import 'package:flutter/material.dart';
import 'package:cloud_firestore/cloud_firestore.dart';
import '../../../../../core/theme/app_colors.dart';
import '../../../../../core/theme/app_radius.dart';
import '../../../../../core/theme/app_spacing.dart';
import '../../../../../core/theme/app_typography.dart';

class AdminBusinessesTab extends StatelessWidget {
  const AdminBusinessesTab({super.key});

  void _approveBusiness(BuildContext context, DocumentSnapshot doc) async {
    final data = doc.data() as Map<String, dynamic>;
    
    // 1. Move to active businesses
    await FirebaseFirestore.instance.collection('businesses').add(data);
    
    // 2. Delete from pending
    await doc.reference.delete();
    
    // 3. Update the user's role to 'business'
    final submittedBy = data['submittedBy'] as String?;
    if (submittedBy != null && submittedBy.isNotEmpty) {
      await FirebaseFirestore.instance.collection('users').doc(submittedBy).update({'role': 'business'});
    }
    
    if (context.mounted) {
       ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Business approved!')));
    }
  }

  void _rejectBusiness(BuildContext context, DocumentSnapshot doc) async {
    await doc.reference.update({'status': 'rejected'});
    if (context.mounted) {
       ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content: Text('Business rejected.')));
    }
  }

  @override
  Widget build(BuildContext context) {
    return Padding(
      padding: EdgeInsets.all(AppSpacing.xl),
      child: Column(
        crossAxisAlignment: CrossAxisAlignment.start,
        children: [
          Text(
            'Business Approvals',
            style: AppTypography.headlineMedium.copyWith(fontWeight: FontWeight.w800),
          ),
          SizedBox(height: AppSpacing.sm),
          Text(
            'Review pending business verifications generated by AI',
            style: AppTypography.bodyMedium.copyWith(color: AppColors.textSecondary),
          ),
          SizedBox(height: AppSpacing.xl),
          Expanded(
            child: StreamBuilder<QuerySnapshot>(
              stream: FirebaseFirestore.instance
                  .collection('pending_businesses')
                  .where('status', isEqualTo: 'pending')
                  .snapshots(),
              builder: (context, snapshot) {
                if (snapshot.hasError) {
                  return Center(child: Text('Error: ${snapshot.error}'));
                }

                if (snapshot.connectionState == ConnectionState.waiting) {
                  return const Center(child: CircularProgressIndicator());
                }

                final pendingDocs = snapshot.data?.docs ?? [];

                if (pendingDocs.isEmpty) {
                  return Center(
                    child: Column(
                      mainAxisAlignment: MainAxisAlignment.center,
                      children: [
                        Icon(Icons.check_circle_outline, size: 64, color: AppColors.success),
                        SizedBox(height: AppSpacing.md),
                        Text('All caught up!', style: AppTypography.headlineSmall),
                        Text('No pending businesses to review.', style: AppTypography.bodyMedium.copyWith(color: AppColors.textSecondary)),
                      ],
                    ),
                  );
                }

                return ListView.builder(
                  itemCount: pendingDocs.length,
                  itemBuilder: (context, index) {
                    final doc = pendingDocs[index];
                    final data = doc.data() as Map<String, dynamic>;
                    
                    return Card(
                      margin: EdgeInsets.only(bottom: AppSpacing.md),
                      shape: RoundedRectangleBorder(borderRadius: BorderRadius.circular(AppRadius.lg)),
                      child: Padding(
                        padding: EdgeInsets.all(AppSpacing.lg),
                        child: Column(
                          crossAxisAlignment: CrossAxisAlignment.start,
                          children: [
                            Row(
                              mainAxisAlignment: MainAxisAlignment.spaceBetween,
                              children: [
                                Text(
                                  data['name'] ?? 'Unknown Business',
                                  style: const TextStyle(fontSize: 20, fontWeight: FontWeight.bold),
                                ),
                                Container(
                                  padding: const EdgeInsets.symmetric(horizontal: 12, vertical: 6),
                                  decoration: BoxDecoration(
                                    color: Colors.orange.withOpacity(0.1),
                                    borderRadius: BorderRadius.circular(AppRadius.full),
                                  ),
                                  child: const Text('Pending Review', style: TextStyle(color: Colors.orange, fontWeight: FontWeight.bold)),
                                ),
                              ],
                            ),
                            const SizedBox(height: 8),
                            Row(
                              children: [
                                Icon(Icons.location_on, size: 16, color: AppColors.textSecondary),
                                const SizedBox(width: 4),
                                Text(data['location'] ?? 'Not provided', style: TextStyle(color: AppColors.textSecondary)),
                              ],
                            ),
                            const Divider(height: 32),
                            const Text('Original Description (By User):', style: TextStyle(fontWeight: FontWeight.bold)),
                            const SizedBox(height: 4),
                            Text(data['original_desc'] ?? ''),
                            const SizedBox(height: 16),
                            Text('Enhanced Description (By AI):', style: TextStyle(fontWeight: FontWeight.bold, color: AppColors.primary)),
                            const SizedBox(height: 4),
                            Text(data['enhanced_desc'] ?? ''),
                            const SizedBox(height: 24),
                            Row(
                              mainAxisAlignment: MainAxisAlignment.end,
                              children: [
                                OutlinedButton(
                                  onPressed: () => _rejectBusiness(context, doc),
                                  style: OutlinedButton.styleFrom(
                                    foregroundColor: AppColors.error,
                                    side: BorderSide(color: AppColors.error),
                                  ),
                                  child: const Text('Reject'),
                                ),
                                const SizedBox(width: 12),
                                ElevatedButton(
                                  onPressed: () => _approveBusiness(context, doc),
                                  style: ElevatedButton.styleFrom(backgroundColor: AppColors.success),
                                  child: const Text('Approve', style: TextStyle(color: Colors.white)),
                                ),
                              ],
                            ),
                          ],
                        ),
                      ),
                    );
                  },
                );
              },
            ),
          ),
        ],
      ),
    );
  }
}
