[build]
  functions = "netlify/functions"

# Redirect all /api requests to the main express app function
[[redirects]]
  from   = "/api/*"
  to     = "/.netlify/functions/api"
  status = 200
  force  = true