[build]
  command = "npm install"
  functions = "functions"
  publish = "."

# Redirect all requests to the main express app function
[[redirects]]
  from   = "/*"
  to     = "/.netlify/functions/api/:splat"
  status = 200
  force  = true