import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

import '../../../../core/theme/app_colors.dart';
import '../../../../core/theme/app_radius.dart';
import '../../../../core/theme/app_spacing.dart';
import '../../../../core/theme/app_typography.dart';
import '../../../../core/widgets/custom_button.dart';
import '../../../auth/presentation/providers/auth_provider.dart';
import '../../../booking/domain/entities/booking_entity.dart';
import '../../domain/entities/review_entity.dart';
import '../providers/review_provider.dart';

class RateAndReviewSheet extends ConsumerStatefulWidget {
  final BookingEntity booking;
  final String reviewerRole; // 'host' or 'seeker'
  final VoidCallback onSuccess;

  const RateAndReviewSheet({
    super.key,
    required this.booking,
    required this.reviewerRole,
    required this.onSuccess,
  });

  @override
  ConsumerState<RateAndReviewSheet> createState() => _RateAndReviewSheetState();
}

class _RateAndReviewSheetState extends ConsumerState<RateAndReviewSheet> {
  int _rating = 0;
  int _hostRating = 0;
  final TextEditingController _messageController = TextEditingController();
  bool _isSubmitting = false;

  @override
  void dispose() {
    _messageController.dispose();
    super.dispose();
  }

  Future<void> _submitReview() async {
    if (_rating == 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please select a rating for the experience.'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    if (widget.reviewerRole == 'seeker' && _hostRating == 0) {
      ScaffoldMessenger.of(context).showSnackBar(
        const SnackBar(
          content: Text('Please select a rating for the host.'),
          backgroundColor: AppColors.error,
        ),
      );
      return;
    }

    setState(() => _isSubmitting = true);

    try {
      final user = ref.read(currentUserProvider).value;
      if (user == null) throw Exception('User not logged in');

      final repository = ref.read(reviewRepositoryProvider);
      
      final String revieweeId = widget.reviewerRole == 'seeker' 
          ? widget.booking.hostId 
          : widget.booking.userId;

      final review = ReviewEntity(
        id: '', // Generated by Firestore
        bookingId: widget.booking.id,
        experienceId: widget.booking.experienceId,
        reviewerId: user.uid,
        revieweeId: revieweeId,
        role: widget.reviewerRole,
        rating: _rating.toDouble(),
        hostRating: widget.reviewerRole == 'seeker' ? _hostRating.toDouble() : null,
        message: _messageController.text.trim().isNotEmpty 
            ? _messageController.text.trim() 
            : null,
        createdAt: DateTime.now(),
      );

      await repository.submitReview(review);

      if (mounted) {
        Navigator.pop(context);
        widget.onSuccess();
        ScaffoldMessenger.of(context).showSnackBar(
          const SnackBar(
            content: Text('Thank you! Your review has been submitted.'),
            backgroundColor: AppColors.success,
          ),
        );
      }
    } catch (e) {
      if (mounted) {
        setState(() => _isSubmitting = false);
        ScaffoldMessenger.of(context).showSnackBar(
          SnackBar(
            content: Text('Failed to submit review: $e'),
            backgroundColor: AppColors.error,
          ),
        );
      }
    }
  }

  @override
  Widget build(BuildContext context) {
    // Title based on who is reviewing whom
    final String titleText = widget.reviewerRole == 'seeker' 
        ? 'Rate your experience' 
        : 'Rate the seeker';
        
    final String subTitleText = widget.reviewerRole == 'seeker'
        ? 'How was your time at "${widget.booking.experienceTitle}"?'
        : 'How was hosting for this booking?';

    return DraggableScrollableSheet(
      initialChildSize: 0.85,
      minChildSize: 0.5,
      maxChildSize: 0.95,
      builder: (_, controller) => Container(
        decoration: const BoxDecoration(
          color: AppColors.background,
          borderRadius: BorderRadius.vertical(top: Radius.circular(AppRadius.xl)),
        ),
        child: ListView(
          controller: controller,
          padding: EdgeInsets.only(
            left: AppSpacing.lg,
            right: AppSpacing.lg,
            top: AppSpacing.sm,
            bottom: MediaQuery.of(context).viewInsets.bottom + AppSpacing.xl,
          ),
          children: [
            // Handle bar
            Center(
              child: Container(
                width: 40,
                height: 4,
                margin: const EdgeInsets.symmetric(vertical: AppSpacing.sm),
                decoration: BoxDecoration(
                  color: AppColors.border,
                  borderRadius: BorderRadius.circular(AppRadius.full),
                ),
              ),
            ),
            const SizedBox(height: AppSpacing.md),

            // Header Icon & Text
            Center(
              child: Container(
                padding: const EdgeInsets.all(16),
                decoration: BoxDecoration(
                  color: AppColors.primary.withAlpha(20),
                  shape: BoxShape.circle,
                ),
                child: const Icon(Icons.star_rounded, color: AppColors.primary, size: 48),
              ),
            ),
            const SizedBox(height: AppSpacing.md),
            
            Text(
              titleText,
              style: AppTypography.headlineSmall.copyWith(
                fontWeight: FontWeight.w800,
                color: AppColors.textPrimary,
              ),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: 4),
            Text(
              subTitleText,
              style: AppTypography.bodyMedium.copyWith(color: AppColors.textSecondary),
              textAlign: TextAlign.center,
            ),
            const SizedBox(height: AppSpacing.xl),

            // Experience Rating
            if (widget.reviewerRole == 'seeker')
              Text(
                'Experience Rating',
                style: AppTypography.labelLarge.copyWith(
                  fontWeight: FontWeight.w700,
                  color: AppColors.textPrimary,
                ),
                textAlign: TextAlign.center,
              ),
            if (widget.reviewerRole == 'seeker')
              const SizedBox(height: AppSpacing.sm),
            Row(
              mainAxisAlignment: MainAxisAlignment.center,
              children: List.generate(5, (index) {
                final isSelected = index < _rating;
                return GestureDetector(
                  onTap: () => setState(() => _rating = index + 1),
                  child: Padding(
                    padding: const EdgeInsets.symmetric(horizontal: 4.0),
                    child: AnimatedContainer(
                      duration: const Duration(milliseconds: 200),
                      curve: Curves.easeOutCubic,
                      transform: isSelected 
                          ? (Matrix4.identity()..scale(1.2)) 
                          : Matrix4.identity(),
                      child: Icon(
                        isSelected ? Icons.star_rounded : Icons.star_outline_rounded,
                        color: isSelected ? const Color(0xFFFFB800) : AppColors.border,
                        size: widget.reviewerRole == 'seeker' ? 36 : 48,
                      ),
                    ),
                  ),
                );
              }),
            ),
            const SizedBox(height: AppSpacing.lg),

            // Host Rating (only if seeker is reviewing)
            if (widget.reviewerRole == 'seeker') ...[
              Text(
                'Host Rating',
                style: AppTypography.labelLarge.copyWith(
                  fontWeight: FontWeight.w700,
                  color: AppColors.textPrimary,
                ),
                textAlign: TextAlign.center,
              ),
              const SizedBox(height: AppSpacing.sm),
              Row(
                mainAxisAlignment: MainAxisAlignment.center,
                children: List.generate(5, (index) {
                  final isSelected = index < _hostRating;
                  return GestureDetector(
                    onTap: () => setState(() => _hostRating = index + 1),
                    child: Padding(
                      padding: const EdgeInsets.symmetric(horizontal: 4.0),
                      child: AnimatedContainer(
                        duration: const Duration(milliseconds: 200),
                        curve: Curves.easeOutCubic,
                        transform: isSelected 
                            ? (Matrix4.identity()..scale(1.2)) 
                            : Matrix4.identity(),
                        child: Icon(
                          isSelected ? Icons.star_rounded : Icons.star_outline_rounded,
                          color: isSelected ? const Color(0xFFFFB800) : AppColors.border,
                          size: 36,
                        ),
                      ),
                    ),
                  );
                }),
              ),
              const SizedBox(height: AppSpacing.xxl),
            ],

            // Optional Message Text Field
            Text(
              'Write a review (Optional)',
              style: AppTypography.labelLarge.copyWith(
                fontWeight: FontWeight.w700,
                color: AppColors.textPrimary,
              ),
            ),
            const SizedBox(height: AppSpacing.sm),
            TextField(
              controller: _messageController,
              maxLines: 4,
              textInputAction: TextInputAction.done,
              decoration: InputDecoration(
                hintText: widget.reviewerRole == 'seeker'
                    ? 'What did you love about this experience?'
                    : 'Were they a great guest?',
                hintStyle: AppTypography.bodyMedium.copyWith(color: AppColors.textSecondary),
                filled: true,
                fillColor: AppColors.surface,
                border: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(AppRadius.md),
                  borderSide: const BorderSide(color: AppColors.border),
                ),
                enabledBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(AppRadius.md),
                  borderSide: const BorderSide(color: AppColors.border),
                ),
                focusedBorder: OutlineInputBorder(
                  borderRadius: BorderRadius.circular(AppRadius.md),
                  borderSide: const BorderSide(color: AppColors.primary),
                ),
              ),
            ),
            const SizedBox(height: AppSpacing.xl),

            // Submit Button
            ZeyloButton(
              onPressed: _isSubmitting ? null : _submitReview,
              label: _isSubmitting ? 'Submitting...' : 'Submit Review',
              isLoading: _isSubmitting,
              variant: ButtonVariant.filled,
            ),
          ],
        ),
      ),
    );
  }
}
