import 'package:dartz/dartz.dart';
import '../../../../core/errors/failures.dart';
import '../../../../core/usecases/usecase.dart';
import '../entities/chain_entity.dart';
import '../repositories/chain_repository.dart';

/// Use case for creating a new chain (mini trip)
///
/// Handles the business logic for creating chains.
/// Validates input and delegates to the repository for data persistence.
class CreateChainUseCase extends UseCase<ChainEntity, CreateChainParams> {
  /// Repository for chain operations
  final ChainRepository repository;

  CreateChainUseCase({required this.repository});

  @override
  Future<Either<Failure, ChainEntity>> call(CreateChainParams params) async {
    return repository.createChain(
      ChainEntity(
        id: '', // ID will be generated by Firebase
        name: params.name,
        description: params.description,
        createdBy: params.userId,
        destinationCity: params.destinationCity,
        date: params.date,
        totalTime: params.totalTime,
        interests: params.interests,
        experiences: params.experiences,
        totalPrice: params.experiences
            .fold(0.0, (sum, exp) => sum + exp.price),
        status: ChainStatus.draft,
        createdAt: DateTime.now(),
      ),
    );
  }
}

/// Parameters for creating a chain
class CreateChainParams {
  /// User ID creating the chain
  final String userId;

  /// Name of the chain
  final String name;

  /// Description of the chain
  final String description;

  /// Destination city
  final String destinationCity;

  /// Date in yyyy-MM-dd format
  final String date;

  /// Total time available
  final ChainDuration totalTime;

  /// Interests for this chain
  final List<String> interests;

  /// Experiences in the chain
  final List<ChainExperience> experiences;

  const CreateChainParams({
    required this.userId,
    required this.name,
    required this.description,
    required this.destinationCity,
    required this.date,
    required this.totalTime,
    required this.interests,
    required this.experiences,
  });
}
